Animated title in detail page
KlubJagiellonski/pola-flutter pull request #117
Opened 2024-08-22 20:02 UTC by WezSieTato

Fix #101

2024-08-23 08:58 UTC, D3bi7 requested changes
Aplikacja nie działa poprawnie, sprawdziłem na telefonie Samsung Galaxy M52 5G z systemem android 13.
Tytuł wyświetla się prawidłowo ale po kliknięciu strzałki do tylu aby się cofnąć zawiesza się cała aplikacja.

2024-08-24 22:36 UTC, WezSieTato commented
Poprawiłem, a przynajmniej na iOSie error się nie pojawia w konsoli (na iOS crasha nie było)

2024-08-27 07:58 UTC, karolgeneral commented
Aplikacja działa poprawnie na telefonie iPhone 7  15.8.2.  Aplikacja działa poprawnie  również na telefonie Samsung A33 z systemem android 14.

2024-08-27 08:08 UTC, karolgeneral approved these changes
Aplikacja działa poprawnie na telefonie iPhone 7 15.8.2. Aplikacja działa poprawnie również na telefonie Samsung A33 z systemem android 14.

2024-08-27 08:17 UTC, merged